// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (service_id, success, status_code, latency)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, success, status_code, latency, created_at
`

type CreateCheckParams struct {
	ServiceID  uuid.UUID `json:"service_id"`
	Success    bool      `json:"success"`
	StatusCode *int32    `json:"status_code"`
	Latency    int32     `json:"latency"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, createCheck,
		arg.ServiceID,
		arg.Success,
		arg.StatusCode,
		arg.Latency,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Success,
		&i.StatusCode,
		&i.Latency,
		&i.CreatedAt,
	)
	return i, err
}
