// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (service_id, success, status_code, latency)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, success, status_code, latency, created_at
`

type CreateCheckParams struct {
	ServiceID  uuid.UUID `json:"service_id"`
	Success    bool      `json:"success"`
	StatusCode *int32    `json:"status_code"`
	Latency    int32     `json:"latency"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, createCheck,
		arg.ServiceID,
		arg.Success,
		arg.StatusCode,
		arg.Latency,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Success,
		&i.StatusCode,
		&i.Latency,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceStats = `-- name: GetServiceStats :one
SELECT
    COUNT(*)::int AS total_checks,
    COUNT(*) FILTER (WHERE success = true)::int AS successful_checks,
    COALESCE(AVG(latency), 0)::int AS avg_latency,
    COALESCE((SELECT c2.latency FROM checks c2 WHERE c2.service_id = $1 ORDER BY c2.created_at DESC LIMIT 1), 0)::int AS last_latency,
    COALESCE((SELECT c3.success FROM checks c3 WHERE c3.service_id = $1 ORDER BY c3.created_at DESC LIMIT 1), false)::bool AS last_success
FROM checks
WHERE service_id = $1
`

type GetServiceStatsRow struct {
	TotalChecks      int32 `json:"total_checks"`
	SuccessfulChecks int32 `json:"successful_checks"`
	AvgLatency       int32 `json:"avg_latency"`
	LastLatency      int32 `json:"last_latency"`
	LastSuccess      bool  `json:"last_success"`
}

func (q *Queries) GetServiceStats(ctx context.Context, serviceID uuid.UUID) (GetServiceStatsRow, error) {
	row := q.db.QueryRow(ctx, getServiceStats, serviceID)
	var i GetServiceStatsRow
	err := row.Scan(
		&i.TotalChecks,
		&i.SuccessfulChecks,
		&i.AvgLatency,
		&i.LastLatency,
		&i.LastSuccess,
	)
	return i, err
}
