// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (service_id, success, status_code, latency)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, success, status_code, latency, created_at
`

type CreateCheckParams struct {
	ServiceID  uuid.UUID `json:"service_id"`
	Success    bool      `json:"success"`
	StatusCode *int32    `json:"status_code"`
	Latency    int32     `json:"latency"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, createCheck,
		arg.ServiceID,
		arg.Success,
		arg.StatusCode,
		arg.Latency,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Success,
		&i.StatusCode,
		&i.Latency,
		&i.CreatedAt,
	)
	return i, err
}

const getLastCheck = `-- name: GetLastCheck :one
SELECT id, service_id, success, status_code, latency, created_at FROM checks
WHERE service_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastCheck(ctx context.Context, serviceID uuid.UUID) (Check, error) {
	row := q.db.QueryRow(ctx, getLastCheck, serviceID)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Success,
		&i.StatusCode,
		&i.Latency,
		&i.CreatedAt,
	)
	return i, err
}

const getUptimeForPeriod = `-- name: GetUptimeForPeriod :one
SELECT
    COUNT(*)::int AS total_checks,
    COUNT(*) FILTER (WHERE success = true)::int AS successful_checks,
    COALESCE(AVG(latency), 0)::int AS avg_latency
FROM checks
WHERE service_id = $1
  AND created_at >= now() - $2::interval
`

type GetUptimeForPeriodParams struct {
	ServiceID uuid.UUID       `json:"service_id"`
	Column2   pgtype.Interval `json:"column_2"`
}

type GetUptimeForPeriodRow struct {
	TotalChecks      int32 `json:"total_checks"`
	SuccessfulChecks int32 `json:"successful_checks"`
	AvgLatency       int32 `json:"avg_latency"`
}

func (q *Queries) GetUptimeForPeriod(ctx context.Context, arg GetUptimeForPeriodParams) (GetUptimeForPeriodRow, error) {
	row := q.db.QueryRow(ctx, getUptimeForPeriod, arg.ServiceID, arg.Column2)
	var i GetUptimeForPeriodRow
	err := row.Scan(&i.TotalChecks, &i.SuccessfulChecks, &i.AvgLatency)
	return i, err
}
