// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationChannelType string

const (
	NotificationChannelTypeEmail   NotificationChannelType = "email"
	NotificationChannelTypeDiscord NotificationChannelType = "discord"
)

func (e *NotificationChannelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannelType(s)
	case string:
		*e = NotificationChannelType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannelType: %T", src)
	}
	return nil
}

type NullNotificationChannelType struct {
	NotificationChannelType NotificationChannelType `json:"notification_channel_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if NotificationChannelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannelType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannelType), nil
}

type NotificationStatus string

const (
	NotificationStatusPending NotificationStatus = "pending"
	NotificationStatusSent    NotificationStatus = "sent"
	NotificationStatusFailed  NotificationStatus = "failed"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus `json:"notification_status"`
	Valid              bool               `json:"valid"` // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type Check struct {
	ID         uuid.UUID          `json:"id"`
	ServiceID  uuid.UUID          `json:"service_id"`
	Success    bool               `json:"success"`
	StatusCode *int32             `json:"status_code"`
	Latency    int32              `json:"latency"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type NotificationChannel struct {
	ID        uuid.UUID               `json:"id"`
	TeamID    uuid.UUID               `json:"team_id"`
	Type      NotificationChannelType `json:"type"`
	Config    []byte                  `json:"config"`
	CreatedAt pgtype.Timestamptz      `json:"created_at"`
}

type NotificationHistory struct {
	ID        uuid.UUID          `json:"id"`
	RuleID    uuid.UUID          `json:"rule_id"`
	ChannelID uuid.UUID          `json:"channel_id"`
	CheckID   uuid.UUID          `json:"check_id"`
	Status    NotificationStatus `json:"status"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
}

type NotificationRule struct {
	ID        uuid.UUID          `json:"id"`
	ServiceID uuid.UUID          `json:"service_id"`
	ChannelID uuid.UUID          `json:"channel_id"`
	Threshold int32              `json:"threshold"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Endpoint  string             `json:"endpoint"`
	Type      string             `json:"type"`
	Interval  int32              `json:"interval"`
	Enabled   bool               `json:"enabled"`
	TeamID    uuid.UUID          `json:"team_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TeamUser struct {
	TeamID    uuid.UUID          `json:"team_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
