// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createNotificationHistory = `-- name: CreateNotificationHistory :one
INSERT INTO notification_history (rule_id, channel_id, check_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, rule_id, channel_id, check_id, status, sent_at
`

type CreateNotificationHistoryParams struct {
	RuleID    uuid.UUID          `json:"rule_id"`
	ChannelID uuid.UUID          `json:"channel_id"`
	CheckID   uuid.UUID          `json:"check_id"`
	Status    NotificationStatus `json:"status"`
}

func (q *Queries) CreateNotificationHistory(ctx context.Context, arg CreateNotificationHistoryParams) (NotificationHistory, error) {
	row := q.db.QueryRow(ctx, createNotificationHistory,
		arg.RuleID,
		arg.ChannelID,
		arg.CheckID,
		arg.Status,
	)
	var i NotificationHistory
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ChannelID,
		&i.CheckID,
		&i.Status,
		&i.SentAt,
	)
	return i, err
}

const getLastNChecksByService = `-- name: GetLastNChecksByService :many
SELECT id, service_id, success, status_code, latency, created_at FROM checks
WHERE service_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetLastNChecksByServiceParams struct {
	ServiceID uuid.UUID `json:"service_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetLastNChecksByService(ctx context.Context, arg GetLastNChecksByServiceParams) ([]Check, error) {
	rows, err := q.db.Query(ctx, getLastNChecksByService, arg.ServiceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Success,
			&i.StatusCode,
			&i.Latency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastNotificationForRule = `-- name: GetLastNotificationForRule :one
SELECT id, rule_id, channel_id, check_id, status, sent_at FROM notification_history
WHERE rule_id = $1
ORDER BY sent_at DESC
LIMIT 1
`

func (q *Queries) GetLastNotificationForRule(ctx context.Context, ruleID uuid.UUID) (NotificationHistory, error) {
	row := q.db.QueryRow(ctx, getLastNotificationForRule, ruleID)
	var i NotificationHistory
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ChannelID,
		&i.CheckID,
		&i.Status,
		&i.SentAt,
	)
	return i, err
}

const getNotificationChannelByID = `-- name: GetNotificationChannelByID :one
SELECT id, team_id, type, config, created_at FROM notification_channels
WHERE id = $1
`

func (q *Queries) GetNotificationChannelByID(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationRulesForService = `-- name: GetNotificationRulesForService :many
SELECT id, service_id, channel_id, threshold, enabled, created_at FROM notification_rules
WHERE service_id = $1 AND enabled = true
`

func (q *Queries) GetNotificationRulesForService(ctx context.Context, serviceID uuid.UUID) ([]NotificationRule, error) {
	rows, err := q.db.Query(ctx, getNotificationRulesForService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRule{}
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.ChannelID,
			&i.Threshold,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
