// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error)
	CreateNotificationHistory(ctx context.Context, arg CreateNotificationHistoryParams) (NotificationHistory, error)
	GetAllServices(ctx context.Context) ([]Service, error)
	GetLastNChecksByService(ctx context.Context, arg GetLastNChecksByServiceParams) ([]Check, error)
	GetLastNotificationForRule(ctx context.Context, ruleID uuid.UUID) (NotificationHistory, error)
	GetNotificationChannelByID(ctx context.Context, id uuid.UUID) (NotificationChannel, error)
	GetNotificationRulesForService(ctx context.Context, serviceID uuid.UUID) ([]NotificationRule, error)
	GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error)
	GetServiceStats(ctx context.Context, serviceID uuid.UUID) (GetServiceStatsRow, error)
}

var _ Querier = (*Queries)(nil)
