// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error)
	GetAllServices(ctx context.Context) ([]Service, error)
	GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error)
}

var _ Querier = (*Queries)(nil)
