// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAllServices = `-- name: GetAllServices :many
SELECT id, name, endpoint, type, interval, enabled, team_id, created_at FROM services WHERE enabled = true
`

func (q *Queries) GetAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Type,
			&i.Interval,
			&i.Enabled,
			&i.TeamID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, endpoint, type, interval, enabled, team_id, created_at FROM services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Type,
		&i.Interval,
		&i.Enabled,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}
